#input data
file_path: './data/train.xlsx'

#save result
output_result: 'result'

#node2vec
walk_length: 30
num_walks: 20
workers: 4
window: 15
node2vec_epoch: 5
min_count: 5
dimensions: 256

#gnn
key_node: 0.2
input_num: 256
hidden_dim_0: 128
hidden_dim_1: 64
output_dim: 2
num_heads: 5

#train config
early_stopping: False
early_stopping_patience: 30

#average_num: 5
seed: 42
learning_rate: 0.01
train_split_ratio: 0.8
num_epochs: 500

